### ISSUE TITLE
Install instructions are wrong

### ISSUE THREAD

**Issue by jarfa** [ua-parser/uap-pig#1]
The stated installation instructions:

> cd ../java ; mvn install
> mvn package

Are not correct, simply because `../java` doesn't exist.

I tried running `mvn install` from `uap-pig/`, but it failed with the error:

> [ERROR] Failed to execute goal on project ua-parser-pig: Could not resolve dependencies for project ua_parser:ua-parser-pig:jar:0.1-SNAPSHOT: Could not find artifact ua_parser:ua-parser:jar:1.3.0-SNAPSHOT -> [Help 1]

Please help. Thanks!

**Comment by nielsbasjes** [comment]
You are right.
I hadn't touched this since the split into multiple sub projects.
I updated the documentation.
