### ISSUE TITLE
Device Family is almost always "Other"

### ISSUE THREAD

**Issue by johnrussell9983** [ua-parser/uap-pig#2]
I'm not sure if this is expected behavior but when I parse real user agents 99% of them come up with a Device Family as "Other". I'd like to at least be able to split this traffic into Desktop vs Mobile. Please contact me with any questions. Thanks!

**Comment by nielsbasjes** [comment]
The uap-pig is really only a pig wrapper around the uap-java implementation.
The uap-java implementation uses the regular expressions in the uap-core.
So if things are wrong in the device family mapping this should be addressed there first.

So my question to you: 
What do you get if you use a different implementation (like python or php) on those useragents?

**Comment by johnrussell9983** [comment]
I have not tried another implementation yet. I will try that out and get back with you. Thanks!

**Comment by johnrussell9983** [comment]
Looks like its an issue with core. They are saying its out of scope for the project. I will close this issue. Thanks!
